# Generated by Django 4.2.24 on 2025-09-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_capitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('contenido', models.TextField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capitulo')),
            ],
        ),
    ]
