# Generated by Django 4.2.24 on 2025-10-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='libro',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='capitulo',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='numero',
            new_name='number',
        ),
    ]
