# Usar Python 3.11
FROM python:3.11-slim

# Crear directorio de trabajo
WORKDIR /app

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código
COPY . .

# Exponer puerto Django
EXPOSE 8000

# 
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
