# Proyecto Backend Python
sonar.projectKey=backend
sonar.projectName=backend
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_81b321442f4f11109a53f70864bdefefe46e63c7
sonar.language=py


